### ISSUE TITLE
Simplify Premium Due Report

### ISSUE THREAD

**Issue by BimaMitra** [BimaMitra/Ultimate#27]
Modify Premium due Report such a way that current Month due, Overdue & Future Months Policies are in different Tabs

**Comment by DeepakJalan** [comment]
Client Mr Kiran Marathe wants to also view only today's premium due & send sms to these customers. He also sent this attachment from other software.
![Screenshot_2019-12-16-16-52-55-164_com perfectandroidappforagents](https://user-images.githubusercontent.com/2452705/70986562-28f50500-20e4-11ea-9f1d-4f823e789522.jpg)

**Comment by BimaMitra** [comment]
Implemented
