### ISSUE TITLE
Accident sum assured issue

### ISSUE THREAD

**Issue by Rajesh-Dhotmal** [BimaMitra/Ultimate#58]
While doing presentation of previous policy accident sum assured is calculating with existing policy.
Actually agent wants to give presentation for the policies which are already sold and added in software but software restricts for accident sum ass and hence problem in showing premium.

**Comment by BimaMitra** [comment]
Moved to BimaMitra Repository
https://github.com/BimaMitra/BimaMitra/issues/71
