### ISSUE TITLE
After Restore Data Data Import Function Not Work

### ISSUE THREAD

**Issue by shahtd1** [BimaMitra/Ultimate#6]
Mail Recd on 31-01-19. Name : Ashok Patel, After Restore data not Shown also Data Import Function Not Working.

**Comment by DeepakJalan** [comment]
@shahtd1 Data Corrected & Mail Sent to Milind

**Comment by milindbhoye** [comment]
Yes I verify Problem Solve and send to Client

**Comment by shahtd1** [comment]
@milindbhoye plz also send to Dealer also

**Comment by milindbhoye** [comment]
Yes mail Send  Rajan Shah
