### ISSUE TITLE
BimaMitra Best Plan Tool not showing all plans.

### ISSUE THREAD

**Issue by milindbhoye** [BimaMitra/Ultimate#9]

**Comment by DeepakJalan** [comment]
PLEASE SEE THE REPORTS OF "BEST PLAN" ATTACHED WHERE I HAVE SELECTED IN OPTION AS "ALL RECORDS" BUT REPORTS IS NOT SHOWING ALL PLANS LIKE 845 NOT MENTIONED AND ALSO FEW OTHER PLANS.

**Comment by milindbhoye** [comment]
BimaMitra Best Plan Tool not showing all plans this bug Shift to Bimamitra
